### ISSUE TITLE
acquire a license file 

### ISSUE THREAD

**Issue by scovitz** [jbteves/archivotron#11]

**Comment by jbteves** [comment]
I for some reason can't assign you, but assigned to @dmoracze

**Comment by dmoracze** [comment]
@jbteves I can't assign myself either, perhaps you need to change the repo permissions?

**Comment by jbteves** [comment]
Apparently you have to comment on an issue to be assigned to it unless you're added with write permissions. That's fine with me since we have branch protection rules anyway.

**Comment by dmoracze** [comment]
@jbteves I've been looking around through the fmrif org repos.

Coder's Forum license: https://github.com/nih-fmrif/coders_forum/blob/master/LICENSE 

machinelearning license: https://github.com/nih-fmrif/machinelearning/blob/master/LICENSE

Neither say anything specific about government property. Thoughts?

**Comment by jbteves** [comment]
Thanks @dmoracze ! Let's just roll with an MIT license.

**Comment by jbteves** [comment]
Closed by #17
