### ISSUE TITLE
Automatically zero pad at the dataset level

### ISSUE THREAD

**Issue by dmoracze** [jbteves/archivotron#7]
Rather than expecting the user to zero pad, say for `subj-01`, the code could read in and index the dataset to determine how many pads are needed.

This would need to be a two (maybe three) step process:

1. Determine if the entity's value is int
2. Count total examples of that entity
3. Zero pad accordingly depending on the total number of that entity

**Comment by jbteves** [comment]
We need to decide a bit about how to build an interface for starting projects, so I'm going to consider this issue paused until that's decided.
